import { format, startOfDay, addDays } from "date-fns";

// Simulation of the bug in analytics.ts
async function simulate() {
  // Use a fixed date to see exact behavior
  const startOfCurrentDate = new Date("2026-03-02T03:00:00Z"); // Start of 02/03 in BRT (UTC-12:00:00 AM)
  const endDate = new Date("2026-03-03T03:00:00Z");

  // Raw result from DB (UTC midnight)
  const results = [
    { day: new Date("2026-03-02T00:00:00.000Z"), revenue: 100 }
  ];

  console.log("DB Result Day (ISO):", results[0].day.toISOString());
  
  // Buggy Mapping in analytics.ts
  const resultMap = new Map(
    results.map((r) => [format(new Date(r.day), "yyyy-MM-dd"), r])
  );
  
  console.log("Map key generated by bug:", Array.from(resultMap.keys())[0]);

  // Gap filling loop in analytics.ts
  let current = startOfDay(new Date(startOfCurrentDate));
  console.log("Gap filling start date (ISO):", current.toISOString());

  const keyToFind = format(current, "yyyy-MM-dd");
  console.log(`Looking for key: ${keyToFind}`);
  
  const data = resultMap.get(keyToFind);
  console.log("Data found:", !!data);
  
  if (!data) {
      console.log("❌ REPRODUCTION SUCCESSFUL: Data lost due to timezone shift.");
  } else {
      console.log("✅ Data found (might be because your environment is in UTC).");
  }
}

simulate();
